### ISSUE TITLE
Problems with example `registration.py`

### ISSUE THREAD

**Issue by cmcqueen** [frawau/aiozeroconf#12]
I see a couple of problems with the example code `registration.py`:

* A `ServiceInfo` object is created and assigned to variable `info` at the file level. But it seems this isn't used for anything. Another one is created in the function `run_test()`, and that seems to actually do something. Is this a mistake with refactoring this code?
* It seems most of the `ServiceInfo` parameters now need to be named parameters, rather than positional.

**Comment by frawau** [comment]
Hi,

Thanks for your comments.  

It is an example, it is just to show what you can do. By all mean, do modify things as you see fit.

Regards

**Comment by cmcqueen** [comment]
As the example currently is, it can't even run — since most of the `ServiceInfo` parameters now need to be named parameters, rather than positional. So could you please fix that? I can submit a pull request if you would like.

**Comment by frawau** [comment]
Hi,Those examples are remnants of some old software, I should have removed them. The one and only example is __main__.pyNow if you want to fix them with a PR, go ahead, I'll merge it in.Regards,      FrançoisOn 15 Feb 2019 05:55, Craig McQueen <notifications@github.com> wrote:As the example currently is, it can't even run — since most of the ServiceInfo parameters now need to be named parameters, rather than positional. So could you please fix that? I can submit a pull request if you would like.
